[package]
name = "graphics"
version = "0.1.0"
edition = "2021"


[dependencies]
 
ash-window = "0.13.0"       
winit = "0.28.0"       
env_logger = "0.11.6" 
log = "0.4"           
ash = "0.37.2"
anyhow = "1.0.95"
